[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flake8]
ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401']
max-line-length = 90
max-complexity = 18
select = ['B','C','E','F','W','T4','B9']

[tool.mypy]
mypy_path="/home/teremyz/.local/share/virtualenvs/mlops-project-z-4QfxLv/lib/python3.7/site-packages"
python_version = "3.7"
ignore_missing_imports = true
exclude = ["requests", "yaml"]
plugins = 'pydantic.mypy'
follow_imports = 'silent'
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = true


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
ignore_missing_imports = true
