name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  MLFOW_EXPERIMENT_ID: 21545d2284b748c3aa462e3f6c903bcf
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7' 
    - name: Update pip
      run: pip install -U pip
      
    - name: Install pipenv
      run: pip install pipenv

    - name: Install python packages
      run: |
        cd prediction_web_service/
        pipenv install --system
        cd ..
      
    - name: Test application
      run: pytest tests/
    
    - name: Build the Docker image
      run: docker build -t 472376749718.dkr.ecr.us-east-1.amazonaws.com/mlops_eco_prediction_web_service:$(date +"%Y-%m-%d-%H-%M") prediction_web_service/.
    
    - name: Run docker iamge and integration test
      run: bash integration_test/integration_test.sh
  
      
      
      
